In [7]:
# Slicing operations in a list
names = ("happy", "dev","Abhishek", "suraj", "Sourabh")

In [2]:
names

('happy', 'dev', 'Abhishek', 'suraj', 'Sourabh')

In [3]:
names[1:3]

('dev', 'Abhishek')

In [4]:
names[1:]

('dev', 'Abhishek', 'suraj', 'Sourabh')

In [5]:
names[:]

('happy', 'dev', 'Abhishek', 'suraj', 'Sourabh')

In [23]:
names[::2]

('happy', 'Abhishek', 'Sourabh')

In [8]:
# List inside a list or a Nested list

In [13]:
students= [
    ["Happy",1111, "mumbai"],
    ["dev", 2222, "jaipur"],
    ["suraj",3333, "delhi"],
    ["Abhishek", 4444, "chandigarh"]
]

In [16]:
students # 2-D list

[['Happy', 1111, 'mumbai'],
 ['dev', 2222, 'jaipur'],
 ['suraj', 3333, 'delhi'],
 ['Abhishek', 4444, 'chandigarh']]

In [15]:
len(students)

4

In [17]:
# We can only print the row content of a list. 
# The list does not allow column-wise operation.

In [18]:
students[1:3]

[['dev', 2222, 'jaipur'], ['suraj', 3333, 'delhi']]

In [34]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [35]:
import numpy

In [36]:
A = numpy.array([1,2,3,4,5])

In [37]:
print(A)

[1 2 3 4 5]


In [38]:
numpy.zeros(2)

array([0., 0.])

In [39]:
numpy.ones(2)

array([1., 1.])

In [40]:
numpy.linspace(0,10, num=10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [48]:
arr = numpy.array([2,6,3,5,7,9,1,4])

In [49]:
arr

array([2, 6, 3, 5, 7, 9, 1, 4])

In [50]:
numpy.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [5]:
x = numpy.array([1,2,3,4,5])
y = numpy.array(["hi", "hello", 1.7, 8])

In [7]:
numpy.concatenate((x,y))

array(['1', '2', '3', '4', '5', 'hi', 'hello', '1.7', '8'], dtype='<U32')

In [8]:
students= [
    ["Happy",1111, "mumbai"],
    ["dev", 2222, "jaipur"],
    ["suraj",3333, "delhi"],
    ["Abhishek", 4444, "chandigarh"]
]

In [9]:
b =numpy.array(students)

In [10]:
print(b)

[['Happy' '1111' 'mumbai']
 ['dev' '2222' 'jaipur']
 ['suraj' '3333' 'delhi']
 ['Abhishek' '4444' 'chandigarh']]


In [11]:
type(b)

numpy.ndarray

In [13]:
b.ndim

2

In [14]:
b.shape

(4, 3)

In [23]:
db= numpy.array([
    "happy",
    "dev",
    "eric",
    "suraj",
    "umesh",
    "rahul"
])

In [24]:
db

array(['happy', 'dev', 'eric', 'suraj', 'umesh', 'rahul'], dtype='<U5')

In [25]:
db.shape

(6,)

In [26]:
db.ndim

1

In [27]:
myteam = db.reshape(3,2)

In [28]:
myteam

array([['happy', 'dev'],
       ['eric', 'suraj'],
       ['umesh', 'rahul']], dtype='<U5')

In [30]:
myteam.flatten().ndim

1

In [31]:
#tuple are immutable and the data cannot be changed once saved.

In [32]:
country = ("india", "USA", "china", "italy")

In [33]:
country

('india', 'USA', 'china', 'italy')